global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
  - job_name: node
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'node-exporter:9100'
  - job_name: 'consul-server'
    metrics_path: '/v1/agent/metrics'
    params:
      format: [prometheus]
    consul_sd_configs:
      - server: 'consul-server:8500'
        datacenter: dc1
        services:
          - consul
    relabel_configs:
      - action: replace
        source_labels: [__meta_consul_address]
        regex: (.+)
        replacement: $1:8500
        target_label: __address__
